name: Dev Workflow

on:
  push:
    branches:
      - feature/*

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Project dependencies
        run: yarn install
      - name: Lint code
        run: yarn preflight
      - name: Build code
        run: yarn build
      - uses: FranzDiebold/github-env-vars-action@v1.3.0
      - name: Get Netlify Cli
        run: yarn global add netlify-cli
      - name: Netlify Deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
        run: netlify deploy --dir=build --message "$GITHUB_REF_NAME $GITHUB_SHA_SHORT $(git log -1 --pretty=format:"%s")" --alias $GITHUB_REF_NAME --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID